//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Library
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Borrow
    {
        [DisplayName("Borrow ID")]
        public int borrow_id { get; set; }
        public string ISBNNO { get; set; }
        [DisplayName("Copy ID")]
        public Nullable<int> copy_id { get; set; }
        [DisplayName("Borrow")]
        public string borrow1 { get; set; }
        [DisplayName("Block")]
        public string block { get; set; }
        [DisplayName("Issue Date")]
        public System.DateTime issue_date { get; set; }
        [DisplayName("Return Date")]
        public Nullable<System.DateTime> return_date { get; set; }
        [DisplayName("User ID")]
        public Nullable<int> user_id { get; set; }
        [DisplayName("Fine")]
        public Nullable<decimal> fine { get; set; }
        [DisplayName("Returned")]
        public string returned { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Book Book { get; set; }
        public virtual Copy Copy { get; set; }
    }
}
