//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Library
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Request
    {
        [DisplayName("Request ID")]
        public int req_id { get; set; }
        [DisplayName("Book Name")]
        public string book_name { get; set; }
        [DisplayName("Publisher")]
        public string publisher { get; set; }
        [DisplayName("Author Name")]
        public string author { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
    
        public virtual user user { get; set; }
    }
}
