//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject.Library
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Requests = new HashSet<Request>();
        }
        
        [DisplayName("Id")]
        public int id { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Name")]
        public string name { get; set; }
        [DisplayName("Department")]
        public string department { get; set; }
        [DisplayName("Phone Number")]
        public string phone_number { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
